
development:
  adapter: postgresql
  encoding: unicode
  database: test1_development
  pool: 5
  username: user1
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test1_test
  pool: 5
  username: user1
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: test1_production
  pool: 5
  username: user1
  password:
